GO        ?= go
BINARY    ?= go-comic-converter
FUZZ_TIME ?= 10s

# Per-package fuzz targets for discoverability
FUZZ_TARGETS = \
	FuzzDecodeBounded \
	FuzzIsSupportedImage \
	FuzzCorruptedImageNeverPanics \
	FuzzValidate \
	FuzzOptionsDeserialize \
	FuzzParsePart \
	FuzzBy


# WASM targets
WASM_DIR     ?= wasm
WASM_BINARY  ?= $(WASM_DIR)/main.wasm

.PHONY: wasm wasm-serve

wasm: $(WASM_BINARY)

$(WASM_BINARY): cmd/wasm/*.go
	GOOS=js GOARCH=wasm $(GO) build -o $@ ./cmd/wasm/
	cp "$$(go env GOROOT)/lib/wasm/wasm_exec.js" $(WASM_DIR)/wasm_exec.js

wasm-serve: $(WASM_BINARY)
	@echo "Open http://localhost:8080 in your browser"
	cd $(WASM_DIR) && python3 -m http.server 8080 2>/dev/null || \
	  go run main.go -serve :8080 2>/dev/null || \
	  echo "Install python3 or go, then run: cd wasm && python3 -m http.server 8080"
.PHONY: all build test vet lint clean cover \
        test-race fuzz fuzz-all clean-testdata

all: build

build:
	$(GO) build -o $(BINARY) .

test:
	$(GO) test -timeout 120s -count=1 -race ./...

vet:
	$(GO) vet ./...

lint:
	golangci-lint run ./...

cover:
	$(GO) test -timeout 120s -count=1 -coverprofile=coverage.out ./...
	$(GO) tool cover -func=coverage.out | tail -5

# Fuzz — run every target for FUZZ_TIME (default 10s) as a smoke check.
# Each target runs sequentially; pass FUZZ_TIME=30s for deeper runs.
fuzz: $(addprefix fuzz-,$(FUZZ_TARGETS))

fuzz-all:
	$(GO) test -fuzz=. -fuzztime=$(FUZZ_TIME) -parallel=1 ./...

fuzz-FuzzDecodeBounded:
	$(GO) test -fuzz=FuzzDecodeBounded -fuzztime=$(FUZZ_TIME) ./internal/pkg/epubimageloader/

fuzz-FuzzIsSupportedImage:
	$(GO) test -fuzz=FuzzIsSupportedImage -fuzztime=$(FUZZ_TIME) ./internal/pkg/epubimageloader/

fuzz-FuzzCorruptedImageNeverPanics:
	$(GO) test -fuzz=FuzzCorruptedImageNeverPanics -fuzztime=$(FUZZ_TIME) ./internal/pkg/epubimageloader/

fuzz-FuzzValidate:
	$(GO) test -fuzz=FuzzValidate -fuzztime=$(FUZZ_TIME) ./internal/pkg/converter/

fuzz-FuzzOptionsDeserialize:
	$(GO) test -fuzz=FuzzOptionsDeserialize -fuzztime=$(FUZZ_TIME) ./internal/pkg/converter/

fuzz-FuzzParsePart:
	$(GO) test -fuzz=FuzzParsePart -fuzztime=$(FUZZ_TIME) ./internal/pkg/sortpath/

fuzz-FuzzBy:
	$(GO) test -fuzz=FuzzBy -fuzztime=$(FUZZ_TIME) ./internal/pkg/sortpath/

test-race:
	$(GO) test -timeout 120s -race -count=1 ./...

# Remove fuzz artifacts generated by failed runs.
# Run this before committing fuzz-discovered edge cases you want to keep.
clean-testdata:
	find . -path '*/testdata/fuzz' -type d -exec rm -rf {} + 2>/dev/null; true

clean:
	rm -f $(BINARY)
	rm -rf /tmp/go-comic-converter-*.tmp
